"""Initial tables

Revision ID: 3d0074b5feab
Revises: a4b81beff2fe
Create Date: 2025-12-03 10:09:37.453822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0074b5feab'
down_revision: Union[str, None] = 'a4b81beff2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('staff', sa.Column('basic_salary', sa.Float(), nullable=False))
    op.add_column('staff', sa.Column('bonus_percentage', sa.Float(), nullable=False))
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('staff', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('staff', 'salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('staff', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('staff', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('staff', 'bonus_percentage')
    op.drop_column('staff', 'basic_salary')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
